lFROM python:3

WORKDIR /usr/src/app

ENV FLASK_APP app.py
 
RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY $FLASK_APP ./
COPY . .

EXPOSE 5000

CMD [ "python", "./*.py" ]

